package co.edu.uniquindio.uniclinica.modelo.enums;

public enum Especialidad {

    MEDICINA_GENERAL,
    CARDIOLOGIA,
    UROLOGIA,
    GINECOLOGIA,
    DERMATOLOGIA,
    ODONTOLOGIA,
    PEDIATRIA,
    ORTOPEDIA,
    NEUROLOGIA,
    OFTALMOLOGIA,
    ANGIOLOGIA,
    GASTROENTEROLOGIA,
    OBSTETRICIA,
    OTORRINOLARINGOLOGIA,
    PSIQUIATRIA,
    NEUMOLOGIA,


}
